### ISSUE TITLE
Very high memory consumption when mounting image from network drive

### ISSUE THREAD

**Issue by swurzinger** [sysprogs/WinCDEmu#10]
I regularily use WinCDEmu inside virtual machines (both VMware and VirtualBox) and had memory issues with WinCDEmu already several times when mounting an image file, which is located on a network drive (SMB). Usually I am running an installer off the mounted image. Over time WinCDEmu (no process visible in Task manager) consumes more and more memory. The memory consumption increases quite fast, after it initially started to increase. As soon as the virtual image is ejected the memory consumption drops to a normal level.

I tried this with ISO and other formats and it seems the image format does not matter.
The issue also happened on multiple systems, including Windows 7 SP1 and Windows XP SP3.

**Comment by sysprogs** [comment]
We are aware of this problem. It happens when some third-party program changes the caching settings causing the system to aggressively cache the files read by WinCDEmu. So far we were not able to pinpoint a specific program responsible for that or reproduce the problem on a clean machine.

**Comment by swurzinger** [comment]
For me it happened on a clean Windows 7 SP1 x86 install without any 3rd party software (except the operating system itself) when installing Microsoft Visual Studio 2013 Community Edition Update 4. So it must be the installer or any other Microsoft software included in the Windows 7 operating system that changes that caching behaviour as no other 3rd party software was involved.

Is there any way to detect whether that caching settings were changed? Or is it even possible to detect when a program does/tries to change these settings?
