### ISSUE TITLE
Add support for physical disk emulation?

### ISSUE THREAD

**Issue by mirh** [sysprogs/WinCDEmu#13]
In particular, the required information are already stored in the supported MDF images. 
So.. I guess it would just be about "exposing" them. Specifically: 
* [Media Physical Signature](http://web.archive.org/web/20030214002942/http://forum.alcohol-software.com/index.php?act=ST&f=10&t=1514)
* [sub-channel](https://github.com/simias/rustation/issues/21) data ([already](https://sourceforge.net/p/cdemu/mailman/message/2473508/#msg2473511) supported perhaps?)
* [seek timings](http://web.archive.org/web/20021212141657/http://sirdavidguy.coolfreepages.com/Angle_Based_Copy_Protections.html)
* [twin sectors](http://web.archive.org/web/20050310032851/http://www.cdfreaks.com/article/136) [displacement](http://home.iprimus.com.au/deo/hosted/TwinPeak/00000000.htm)
* [weak sectors](http://www.cdmediaworld.com/hardware/cdrom/cd_protections_safedisc_v2.shtml)

I think a good starting point might be [this](http://web.archive.org/web/20040416030240/http://www.cdfreaks.com/news/9502). 
Of course I'm not asking this to be *specific* to game backups, so no problems if something is still left out.

**Comment by sysprogs** [comment]
Thanks for the suggestion. We probably won't be able to allocate enough resources for this, but if anyone is willing to contribute a patch, we may consider it.
